### ISSUE TITLE
error dired-annotator--get-annotation-for: Wrong type argument: hash-table-p, nil

### ISSUE THREAD

**Issue by ouboub** [gunther-bachmann/emacs-dired-annotator#1]
Hi

thanks for the nice package, it seems to be precisely what I was looking for. 
I cloned and compiled (with Emacs 29 git master from may 2022)
but I obtain 
```
dired-annotator--get-annotation-for: Wrong type argument: hash-table-p, nil
```
when running 
dired-annotator-edit-note

i tried to debug the error
it occurs here
           (annotation (or (dired-annotator--get-annotation-for absolute-file-name)

and later in 
  (or (gethash (dired-annotator--fi-hash file-information) dired-annotator--hash-2-annotation)

Uwe Brauer

**Comment by gunther-bachmann** [comment]
Thanks for noting this issue. I'll look into this.

**Comment by gunther-bachmann** [comment]
I guess this may happen if the hash map is not initialized yet. With the upcoming commit I will make sure that the hash maps are initialized. However, if `dired-annotator--load-annotation-info-from-folder` wasn't executed, the hash will probably not contain any annotations read from the folder (if there are existing ones). 
So it looks like the custom variable `dired-annotator-annotations-folder` is not configured yet. Please make sure to set this variable to a folder where you want to store the actual annotation files.

**Comment by gunther-bachmann** [comment]
I'll add this to the readme since this is not document yet!

**Comment by ouboub** [comment]
>>> "GB" == Gunther Bachmann ***@***.***> writes:

> I guess this may happen if the hash map is not initialized yet. With
> the upcoming commit I will make sure that the hash maps are
> initialized. However, if
> `dired-annotator--load-annotation-info-from-folder` wasn't executed,
> the hash will probably not contain any annotations read from the
> folder (if there are existing ones).
> So it looks like the custom variable
> `dired-annotator-annotations-folder` is not configured yet. Please
> make sure to set this variable to a folder where you want to store the
> actual annotation files.

Well, describe-variable tells me:
,----
| dired-annotator-annotations-folder is a variable defined in ‘dired-annotator.el’.
| 
| Its value is "/home/oub/documents/annotations"
| 
| location for annotation files
| 
|   You can customize this variable.
`----

Hm, ok that directory does not exist, hm. I created the directory, but it seems not to help.


-- 
Warning: Content may be disturbing to some audiences
I strongly condemn Putin's war of aggression against the Ukraine.
I support to deliver weapons to Ukraine's military. 
I support the ban of Russia from SWIFT.
I support the EU membership of the Ukraine. 
https://addons.thunderbird.net/en-US/thunderbird/addon/gmail-conversation-view/

**Comment by ouboub** [comment]
>>> "GB" == Gunther Bachmann ***@***.***> writes:

> I guess this may happen if the hash map is not initialized yet. With
> the upcoming commit I will make sure that the hash maps are
> initialized. However, if
> `dired-annotator--load-annotation-info-from-folder` wasn't executed,
> the hash will probably not contain any annotations read from the
> folder (if there are existing ones).
> So it looks like the custom variable
> `dired-annotator-annotations-folder` is not configured yet. Please
> make sure to set this variable to a folder where you want to store the
> actual annotation files.

Well it seems that the point was: the default directory, did not exist.
After creating and **restarting** emacs
I can now add a note, which looks a bit strange, namely 
,----
| 
| #+title: dired-annotator.el
| #+property: file-information ("Unmatched '.
| Unmatched '.
| " "/home/oub/ALLES/src/emacs-dired-annotator/" "dired-annotator.el" 31612 "2022-11-02T17:50:55" immutable-location)
| * Notes                                                               :elisp:
|   some notes: this looks very interesting
`----

I am not sure, what to think about the 
| #+property: file-information ("Unmatched '.

I am also not sure how to finish the note, simple saving the file and kill the buffer?

**Comment by gunther-bachmann** [comment]
Yeah, Unmatched ' seems not to be right. It should be something like: `#+property: file-information ("0759d799545f0a7ac7e7d95be336f357" "/mount/60a68d4f-b024-4f57-959a-7f3c91ebfa2d/movies/" "bla_bla.mkv" 1189396879 "2022-06-12T16:31:38" immutable-file)`
I usually replace `* Note\n some notes` with the actual annotation text.

**Comment by gunther-bachmann** [comment]
Seems like the hashing did not work (call to md5 and getting the result). I'll take a look.

**Comment by gunther-bachmann** [comment]
I added a safer mode to pass filenames (quoted) into the shell commands. Maybe this helps. But since your file does not seem contain string that should be quoted, it probably is still not fixed.
I will add some debugging log output that could help to find out why the md5 hash is not properly fetched.

**Comment by ouboub** [comment]
the latest commit (7f88c2e47633ae634ab2b) seems to have fixed that table-hash problem

**Comment by gunther-bachmann** [comment]
cool.
