### ISSUE TITLE
the more complex setting, does not work at all

### ISSUE THREAD

**Issue by ouboub** [gunther-bachmann/emacs-dired-annotator#4]
The final test, I used in my init file 
```
(use-package dired-annotator
  :after (posframe all-the-icons org-ql dired-narrow)
  :load-path "~/repo/emacs-dired-annotator"
  :custom ((dired-annotator-note-icon (all-the-icons-faicon "sticky-note"))
           (dired-annotator-annotations-folder (expand-file-name "~/documents/annotations"))
           (dired-annotator-note-popup-hook #'dired-annotator--posframe-note-popup)
           (dired-annotator-note-fill-column 54) ;; a bit smaller than the popup window
           (dired-annotator-note-popup-remove-hook '(dired-annotator-register-buffer-cleanup
                                                     dired-annotator--remove-all-posframes)))
  :hook (dired-mode . dired-annotator-check-dir-local-show)
  :init
  (defconst dired-annotator-note-popup-width 56 "width of the note that pops up")
  (defconst dired-annotator-note-popup-height 40 "max height of the note that pops up")

  (defun dired-annotator--remove-all-posframes ()
    "remove all posframes"
    (unless (eq 'dired-annotator-show-note (lookup-key dired-mode-map (this-single-command-keys)))
      (setq dired-annotator--note-should-not-popup nil))
    (ignore-errors
      (posframe-hide-all)))

  (defun dired-annotator--posframe-note-popup (position annotation-file)
    (setq dired-annotator--note-should-not-popup t)
    (let ((note-buffer (find-file-noselect annotation-file)))
      (with-current-buffer note-buffer
        ;; make sure that regardless of org startup visibility, the buffer is fully visible
        (org-show-all))
      (posframe-show note-buffer :position position :lines-truncate t
                     :width dired-annotator-note-popup-width
                     :border-color "plum4" :border-width 2 :left-fringe 3 :right-fringe 3 )))

  :bind (:map dired-mode-map
              ("C-c a r" . #'dired-annotator-reload-annotation-info)
              ("C-c a d" . #'dired-annotator-dired-on-annotation-folder)
              ("C-c a s" . #'dired-annotator-show-icons)
              ("C-c a h" . #'dired-annotator-hide-icons)
              ("C-c a k" . #'dired-annotator-delete-note)
              ("C-c a o" . #'dired-annotator-edit-note)
              ("C-c a e" . #'dired-annotator-edit-note)
              ("C-c a a" . #'dired-annotator-show-note)
              ("C-c a /" . #'dired-annotator-narrow-on-tag)
              ("'" . #'dired-annotator-show-note)))
```
and have **all** the packages mentioned installed.

however now after restarting emacs, 
the keybinding does not work nor are the functions of dired-annotator known to emacs,
so something in the initialization did not work

Uwe Brauer

**Comment by gunther-bachmann** [comment]
I'll take a look at that, too. I do have a very very similar initialization working in my emacs conf, so this can be only some typo I have in this config.

**Comment by gunther-bachmann** [comment]
Just to make sure: did you adjust the `:load-path` according to the folder you checked this repo out?
From a previous issue I would think this could be `:load-path "/home/oub/ALLES/src/emacs-dired-annotator"`.

**Comment by ouboub** [comment]
>>> "GB" == Gunther Bachmann ***@***.***> writes:

> Just to make sure: did you adjust the `:load-path` according to the folder you checked this repo out?
> From a previous issue I would think this could be `:load-path "/home/oub/ALLES/src/emacs-dired-annotator"`.


Well, at first not 😱

But in my second intent yes, then the functions defined in 
emacs-dired-annotator are found, but the keybinding is not working, while with the simpler setting it is, but no icons not graphics nothing fancy... Hm

**Comment by gunther-bachmann** [comment]
I actually don't know why this could happen. One idea would be to replace the keybindings with the working keybindings of the simpler settings. If that is working, you could possibly identify the keybinding that is responsible for the more complex setting to fail. Since I have the complex keybinding working on my machine, I don't know why this happens.

**Comment by gunther-bachmann** [comment]
Do you still have the problem with a non working complex setup?

**Comment by ouboub** [comment]
>>> "GB" == Gunther Bachmann ***@***.***> writes:

> Do you still have the problem with a non working complex setup?

Yes I do, but on the other hand I am pleased with the simple setup and currently have no need (and time) to look into the complex setup. So I leave it to you to close this issue.
