### ISSUE TITLE
are the annotations permanent?

### ISSUE THREAD

**Issue by ouboub** [gunther-bachmann/emacs-dired-annotator#5]
Hi

although I sent you a personal message, the issue might be of general interest and that is why I open also a new issue, sorry for the double posting....

With the last commit (37f88c2e4763) now

    1.  dired-annotator freshly compiled, Emacs restarted, the functions
        dired-annotator-edit-note, 
        dired-annotator-show-icons and dired-annotator-show-note work!

    2. However only for one session, after restarting emacs:
       dired-annotator-show-icons does not show anything nor
       dired-annotator-show-note work!

    Is this a bug or an implementation detail?

**Comment by gunther-bachmann** [comment]
Only idea I have there is that maybe the properties of the annotation files are not read correctly.
Each annotation file holds an entry `#+property fileinformation ...` which is read when starting to use dired-annotator. If this is not read correctly, the annotation is not / no longer associated with the originally referenced file.
I added some more logging output to do checks on that.
Hope that helps.

**Comment by ouboub** [comment]
Solved with commit **bd6662ca8fa5**
